---
- name: Deploy Hello Kuberentes App
  hosts: initkubmaster
  become: true
  tasks:
  - name: Copy Hello Kuberentes manifest
    copy:
      src: ../manifests/hello-kubernetes/hello-kubernetes.yaml
      dest: "/tmp/hello-kubernetes.yaml"
  - name: Deploy Hello Kuberentes manifest
    become: true
    become_user: "{{ kubectl_user }}"
    shell: "~/.istioctl/bin/istioctl kube-inject -f /tmp/hello-kubernetes.yaml | kubectl apply -f -"
    register: hello_kuberentes_deployment_result
  - name: Show Hello Kubernetes deployment result
    debug:
      msg: "{{ hello_kuberentes_deployment_result }}"
