---
- name: Ensure Helm is installed
  tags: 
    - prepare
  import_playbook: install-helm3.yaml

- name: Setup helm repo 
  tags: 
    - prepare
  hosts: initkubmaster
  become: true
  gather_facts: False
  tasks:
  - name: Include vars from vars.yaml
    include_vars:
      file: vars.yaml
  - name: Ensure prometheus-community helm repo is added 
    become_user: "{{ kubectl_user }}"
    command: /usr/local/bin/helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    register: repo_add_result
  - name: Show repo add resul
    debug:
      var: repo_add_result

- name: Install chart
  tags: 
    - install_chart
  hosts: initkubmaster
  become: true
  gather_facts: False
  tasks:
  - name: Include vars from vars.yaml
    include_vars:
      file: vars.yaml
  - name: Ensure prometheus-community helm repo is up to date
    become_user: "{{ kubectl_user }}"
    command: /usr/local/bin/helm repo update
    register: repo_update_result
  - name: Show repo update result
    debug:
      var: repo_add_result
  - name: Template vars.yaml
    template:
      src: ../helm-values/kube-prometheus-stack/values.tmpl.yaml
      dest: "/tmp/kube-prometheus-stack-helm-values.yaml"
  - name: Ensure chart is installed
    become_user: "{{ kubectl_user }}"
    command: /usr/local/bin/helm install -f /tmp/kube-prometheus-stack-helm-values.yaml kube-prometheus-stack prometheus-community/kube-prometheus-stack
    register: helm_install_result
  - name: Show helm install result
    debug:
      var: helm_install_result