--- 
- name: Install istioctl
  tags: 
    - prepare
  hosts: initkubmaster
  become: true
  tasks:
  - name: Check if istioctl is already installed
    stat:
      path: "~{{ kubectl_user }}/.istioctl/bin/istioctl"
    register: stat_istioctl
  - name: Install istioctl
    become: true
    become_user: "{{ kubectl_user }}"
    shell: "curl -sL https://istio.io/downloadIstioctl | sh -"
    when: not stat_istioctl.stat.exists
  - name: Ensure that istioctl is added to user path
    become: true
    become_user: "{{ kubectl_user }}"
    lineinfile:
        path: "~{{ kubectl_user }}/.bashrc"
        line: export PATH=$PATH:$HOME/.istioctl/bin
        
- name: Deploy istio
  hosts: initkubmaster
  become: true
  tasks:
  - name: Register existence of istio operator deployment
    become: true
    become_user: "{{ kubectl_user }}"
    command: kubectl -n istio-operator get deployment istio-operator
    register: istio_operator_deployments
    ignore_errors: yes
  - debug:
      var: istio_operator_deployments.stdout_lines | length
  - name: Deploy istio operator
    become: true
    become_user: "{{ kubectl_user }}"
    command: "~{{ kubectl_user }}/.istioctl/bin/istioctl operator init"
    when: istio_operator_deployments.stdout_lines | length == 0
  - name: Register existence of istio-system namespace
    become: true
    become_user: "{{ kubectl_user }}"
    command: kubectl get namespace istio-system
    register: istio_system_namespace_register
    ignore_errors: yes
  - name: Create istio-system namespace
    become: true
    become_user: "{{ kubectl_user }}"
    command: kubectl create ns istio-system
    when: istio_system_namespace_register.stdout_lines | length == 0
  - name: Template istio default configuration profile manifest
    template:
      src: ../manifests/istio/istio-operator-default-configuaration-profile.tmpl.yaml
      dest: "/tmp/istio-operator-default-configuaration-profile.yaml"
  - name: Install istio default configuration profile
    become: true
    become_user: "{{ kubectl_user }}"
    command: kubectl apply -f /tmp/istio-operator-default-configuaration-profile.yaml
 