---
- name: Ensure Helm is installed
  tags: 
    - prepare
  import_playbook: install-helm3.yaml

- name: Setup helm repo 
  tags: 
    - prepare
  hosts: initkubmaster
  become: true
  gather_facts: False
  tasks:
  - name: Ensure gitpod.io helm repo is added 
    become_user: "{{ kubectl_user }}"
    command: /usr/local/bin/helm repo add gitpod.io https://charts.gitpod.io
    register: repo_add_result
  - name: Show repo add resul
    debug:
      var: repo_add_result

- name: Install chart
  tags: 
    - install_chart
  hosts: initkubmaster
  become: true
  gather_facts: False
  tasks:
  - name: Ensure gitpod.io helm repo is up to date
    become_user: "{{ kubectl_user }}"
    command: /usr/local/bin/helm repo update
    register: repo_update_result
  - name: Show repo update result
    debug:
      var: repo_update_result
  - name: Label workload_meta nodes
    become_user: "{{ kubectl_user }}"
    command: kubectl label --overwrite nodes {{node}} gitpod.io/workload_meta=true
    loop: "{{gitpod.nodeLabels.workload_meta}}"
    loop_control:
      loop_var: node
  - name: Label workload_workspace nodes
    become_user: "{{ kubectl_user }}"
    command: kubectl label --overwrite nodes {{node}} gitpod.io/workload_workspace=true
    loop: "{{gitpod.nodeLabels.workload_workspace}}"
    loop_control:
      loop_var: node
  - name: Template values
    template:
      src: ../helm-values/gitpod/values.tmpl.yaml
      dest: "/tmp/gitpod-helm-values.yaml"
  - name: Ensure chart is installed
    become_user: "{{ kubectl_user }}"
    command: /usr/local/bin/helm upgrade -i -f /tmp/gitpod-helm-values.yaml gitpod gitpod.io/gitpod --namespace {{gitpod.namespace | default('gitpod')}} --create-namespace --timeout 600s
    register: helm_install_result
  - name: Show helm install result
    debug:
      var: helm_install_result