---
- name: Setup kuernetes masters
  hosts: kubmasters
  become: true
  tasks:
  - name: Include vars from vars.yaml
    include_vars:
      file: vars.yaml 
  - name: Ensure that required ports are open on internal zone
    ansible.posix.firewalld:
      zone: "{{ internal_zone  }}"
      port: "{{ item }}"
      permanent: yes
      state: enabled
    loop: "{{ master_internal_open_ports  }}"
  - name: Register kubernetes admin.conf file existence
    stat:
      path: /etc/kubernetes/admin.conf
    register: k8s_conf_exists
#  - name: Run kubadm init when kubernetes admin.conf file does not exist

