---
- name: Setup kubernetes masters
  hosts: kubmasters
  become: true
  tasks:
  - name: Include vars from vars.yaml
    include_vars:
      file: vars.yaml 
  - name: Ensure that required ports are open on internal zone
    ansible.posix.firewalld:
      zone: "{{ internal_zone  }}"
      port: "{{ item }}"
      permanent: yes
      state: enabled
    loop: "{{ master_internal_open_ports  }}"
  - name: Ensure docker service is enabled and started
    service:
      name: docker
      enabled: yes
      state: started
  - name: Ensure kubelet service is enabled and started
    service:
      name: kubelet
      enabled: yes
      state: started
