---
- name: Test internal networking is properly setup
  hosts: kuball
  gather_facts: True
  vars: 
    ips: "{% set IP_ARR=[] %}{% for host in groups['kuball'] %}{% if IP_ARR.insert(loop.index,hostvars[host]['ansible_'+internal_interface]['ipv4']['address']) %}{% endif %}{% endfor %}{{IP_ARR}}" 
    times: 10
  tasks:
  - name: Include vars from vars.yaml
    include_vars:
      file: vars.yaml
  - debug:
      msg: "{{ ips }}"
  - name: Ping kuball internal ips
    command:
      argv:
        - ping
        - "-c {{ times }}"
        - "{{ item }}"
    loop: "{{ips}}"
  - name: Ping kuball by hostname
    command:
      argv:
        - ping
        - "-c {{ times }}"
        - "{{ item }}"
    loop: "{{groups['kuball']}}"
  - name: Can reach google
    uri:
      url: http://google.com
