apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{gitlab.namespace | default("gitlab")}}.registry
  namespace: istio-system
spec:
  dnsNames:
  {{gitlab.registry.istioHttpsIngress.dns | to_nice_yaml | indent(2)}}
  secretName: {{gitlab.namespace | default("gitlab")}}.registry-certificate
  issuerRef:
    name: {{gitlab.registry.istioHttpsIngress.certificateIssuer}}
    kind: ClusterIssuer
  commonName: {{gitlab.registry.istioHttpsIngress.dns[0]}}

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: registry
  namespace: {{gitlab.namespace | default("gitlab")}}
spec:
  selector:
    istio: {{gitlab.registry.istioHttpsIngress.istioGatewaySelector}}
  servers:
  - port:
      number: {{gitlab.registry.istioHttpsIngress.port | default(443) | int}}
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{gitlab.namespace | default("gitlab")}}.registry-certificate
    hosts:
    {{gitlab.registry.istioHttpsIngress.dns | to_nice_yaml | indent(4)}}

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: registry
  namespace: {{gitlab.namespace | default("gitlab")}}
spec:
  hosts:
  {{gitlab.registry.istioHttpsIngress.dns | to_nice_yaml | indent(2)}}
  gateways:
  - registry
  http:
  - match:
    - uri:
        prefix: {{gitlab.registry.istioHttpsIngress.uriPrefix | default("/")}}
    route:
    - destination:
        port:
          number: 5000
        host: gitlab-registry