apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: default-istio-controlplane
spec:
  profile: default
{% if istio_operator.ingressGateways is defined %}
  components:
    ingressGateways:
{% for gateway in istio_operator.ingressGateways %}
    - name: {{gateway.name}}
{% if gateway.enabled is defined %}
      enabled: {{gateway.enabled}}
{% endif %} 
{% if gateway.overlays is defined or gateway.defaultOverlays | default(false) | bool %}
      k8s:
        replicaCount: {{gateway.replicaCount | default(1)}}
        overlays:
{% if gateway.defaultOverlays | default(false) | bool %}
{% macro defaultOverlays() %}
{% with name = gateway.name | regex_replace('^istio-',''), overlays = gateway.overlays | default([]), indent = 8 %}
{% include './ingress-gateway-default-overlays.tmpl.yaml' %}
{% endwith %}
{% endmacro %}
        {{ defaultOverlays() | indent(8) }}
{% elif gateway.overlays is defined %}
        {{gateway.overlays | to_nice_yaml | indent(8)}}
{% endif %} 
{% endif %}  
{% endfor %}
{% endif %}
