namespaceOverride: {{kube_prometheus_stack.namespace | default("kube-prometheus")}}
## Configuration for alertmanager
## ref: https://prometheus.io/docs/alerting/alertmanager/
##
alertmanager:

  ## Settings affecting alertmanagerSpec
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#alertmanagerspec
  ##
  alertmanagerSpec:
    
    ## Storage is the definition of how storage will be used by the Alertmanager instances.
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/storage.md
    ##
    storage: 
      volumeClaimTemplate:
        spec:
          storageClassName: {{kube_prometheus_stack.alertmanager.storage.storageClassName | default("gluster")}}
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: {{kube_prometheus_stack.alertmanager.storage.requestSize | default("50Gi")}}
    # volumeClaimTemplate:
    #   spec:
    #     storageClassName: gluster
    #     accessModes: ["ReadWriteOnce"]
    #     resources:
    #       requests:
    #         storage: 50Gi
    #   selector: {}

## Deploy a Prometheus instance
##
prometheus:
  prometheusSpec:
    ## Interval between consecutive scrapes.
    ## Defaults to 30s.
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/release-0.44/pkg/prometheus/promcfg.go#L180-L183
    ##
    scrapeInterval: {{kube_prometheus_stack.prometheus.scrapeInterval | default("")}}
    evaluationInterval: {{kube_prometheus_stack.prometheus.evaluationInterval | default("")}}
    ## Prometheus StorageSpec for persistent data
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/storage.md
    ##
    storageSpec: 
      volumeClaimTemplate:
        spec:
          storageClassName: {{kube_prometheus_stack.prometheus.storage.storageClassName | default("gluster")}}
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: {{kube_prometheus_stack.prometheus.storage.requestSize | default("50Gi")}}
    ## Using PersistentVolumeClaim
    ##
    #  volumeClaimTemplate:
    #    spec:
    #      storageClassName: gluster
    #      accessModes: ["ReadWriteOnce"]
    #      resources:
    #        requests:
    #          storage: 50Gi
    #    selector: {}
{%if kube_prometheus_stack.prometheus.resources is defined %}
    resources: 
      {{kube_prometheus_stack.prometheus.resources | to_nice_yaml | indent(6)}} 
{% endif %}

grafana:
  namespaceOverride: {{kube_prometheus_stack.namespace | default("kube-prometheus")}}
  persistence:
    enabled: true
    type: pvc
    storageClassName: {{kube_prometheus_stack.grafana.storage.storageClassName | default("gluster")}}
    accessModes:
    - ReadWriteOnce
    size: {{kube_prometheus_stack.grafana.storage.requestSize | default("4Gi")}}

kube-state-metrics:
  namespaceOverride: {{kube_prometheus_stack.namespace | default("kube-prometheus")}}

prometheus-node-exporter:
  namespaceOverride: {{kube_prometheus_stack.namespace | default("kube-prometheus")}}